packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - msgpackr-extract
  - msw
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - vite
  - vitest
  - '@nestjs/cli'
